#!/usr/bin/env python3
"""
Peace Paths — Test Environment Server
======================================
Serves the production frontend from test/app/ on :8766.
Data source: app/data.json (generated by local AI pipeline).
Used to verify frontend rendering against real AI-generated data
before committing and pushing to GitHub.
"""

import datetime
import http.server
import json
import os
import subprocess
import sys
import threading
import time
from pathlib import Path

# Fix Windows console encoding
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

PORT = 8766
PROJECT_ROOT = Path(__file__).parent.parent
DATA_SOURCE = PROJECT_ROOT / "app" / "data.json"
SERVE_DIR = Path(__file__).parent / "app"
CATEGORIES_FILE = PROJECT_ROOT / "categories.json"
PROMPTS_FILE = PROJECT_ROOT / "prompts.json"
TAXONOMY_FILE = PROJECT_ROOT / "taxonomy.json"

# ── Data sync ──────────────────────────────────────────
# The test env reads app/data.json directly (no copy needed).
# The frontend fetches /data.json which the server proxies.

_cached_data = None
SCRIPT = PROJECT_ROOT / "ai-analyze-prod.py"  # Root pipeline
analysis_status = {
    "running": False, "pid": None, "started": None, "log": "", "proc": None,
    "stages": {
        "fetch": {"label": "Fetching RSS", "icon": "📡", "done": False, "count": 0, "detail": ""},
        "classify": {"label": "Classifying", "icon": "🧠", "done": False, "count": 0, "detail": ""},
        "cluster": {"label": "Clustering", "icon": "🔗", "done": False, "count": 0, "detail": ""},
        "phase": {"label": "Determining Phases", "icon": "🗺️", "done": False, "count": 0, "detail": ""},
        "narrative": {"label": "Generating Narratives", "icon": "📝", "done": False, "count": 0, "detail": ""},
        "shift": {"label": "Detecting Shifts", "icon": "🔍", "done": False, "count": 0, "detail": ""},
        "translate": {"label": "Translating", "icon": "🌐", "done": False, "count": 0, "detail": ""},
        "output": {"label": "Writing Output", "icon": "💾", "done": False, "count": 0, "detail": ""},
    },
    "current_stage": None,
    "pct": 0,
}

def _parse_log_line(text, stages, status):
    """Parse a log line and update stage tracking."""
    import re
    # RSS fetch: "→ 295 articles fetched"
    m = re.search(r'→\s*(\d+)\s+articles?\s+fetched', text)
    if m:
        stages["fetch"]["done"] = True
        stages["fetch"]["count"] = int(m.group(1))
        stages["fetch"]["detail"] = f'{int(m.group(1))} articles'
        status["current_stage"] = "fetch"
        status["pct"] = 5
        return
    # Classification progress: "[100/184 (54%)] 150 relevant, 34 dropped"
    m = re.search(r'\[(\d+)/(\d+)\s+\((\d+)%\)\]', text)
    if m:
        stages["classify"]["count"] = int(m.group(1))
        stages["classify"]["detail"] = f'{m.group(1)}/{m.group(2)} ({m.group(3)}%)'
        status["current_stage"] = "classify"
        status["pct"] = 10 + int(m.group(3))
        return
    # Classification total: "Total: 211 relevant"
    m = re.search(r'Total:\s*(\d+)\s+relevant', text)
    if m:
        stages["classify"]["done"] = True
        stages["classify"]["count"] = int(m.group(1))
        stages["classify"]["detail"] = f'{int(m.group(1))} relevant'
        status["pct"] = 40
        return
    # Clustering: "→ 128 clusters from 184 articles"
    m = re.search(r'→\s*(\d+)\s+clusters?\s+from\s+(\d+)', text)
    if m:
        stages["cluster"]["done"] = True
        stages["cluster"]["count"] = int(m.group(1))
        stages["cluster"]["detail"] = f'{int(m.group(1))} clusters from {m.group(2)} articles'
        status["current_stage"] = "cluster"
        status["pct"] = 50
        return
    # Phase: "✓ Phases for 6 solutions"
    m = re.search(r'✓\s+Phases\s+for\s+(\d+)', text)
    if m:
        stages["phase"]["done"] = True
        stages["phase"]["count"] = int(m.group(1))
        stages["phase"]["detail"] = f'{int(m.group(1))} solutions'
        status["current_stage"] = "phase"
        status["pct"] = 60
        return
    # Narrative: "✓ {name}: narrative generated" or "Generating narratives for 6 solutions"
    if "Generating narratives for" in text:
        m = re.search(r'for\s+(\d+)', text)
        if m:
            stages["narrative"]["count"] = int(m.group(1))
            status["current_stage"] = "narrative"
            status["pct"] = 65
    if ": narrative generated" in text or ": fallback narrative" in text:
        stages["narrative"]["done"] = True
        status["pct"] = 75
        return
    # Shift: "✓ 3 shifts detected"
    m = re.search(r'✓\s+(\d+)\s+shifts?\s+detected', text)
    if m:
        stages["shift"]["done"] = True
        stages["shift"]["count"] = int(m.group(1))
        stages["shift"]["detail"] = f'{int(m.group(1))} shifts'
        status["current_stage"] = "shift"
        status["pct"] = 80
        return
    # Translate: "🌐 Translating 42 unique texts"
    m = re.search(r'Translating\s+(\d+)\s+unique', text)
    if m:
        stages["translate"]["done"] = True
        stages["translate"]["count"] = int(m.group(1))
        stages["translate"]["detail"] = f'{int(m.group(1))} texts'
        status["current_stage"] = "translate"
        status["pct"] = 88
        return
    # Output: "Written to" or "Done in"
    if "Written to" in text or "Done in" in text:
        stages["output"]["done"] = True
        status["current_stage"] = "output"
        status["pct"] = 95
        return


def run_analysis(mode="--fast"):
    """Run ai-analyze-prod.py in the background."""
    global analysis_status, _cached_data
    env = os.environ.copy()
    env.setdefault("LLAMA_CPP_URL", os.environ.get("LLAMA_CPP_URL", "http://localhost:8080"))
    env["PYTHONIOENCODING"] = "utf-8"
    cmd = [sys.executable, str(SCRIPT), mode, "--skip-upload"]
    log_lines = []
    try:
        print(f"\n  [Analysis] Starting: {' '.join(cmd)}")
        proc = subprocess.Popen(
            cmd, env=env,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            creationflags=subprocess.CREATE_NO_WINDOW
        )
        analysis_status["running"] = True
        analysis_status["pid"] = proc.pid
        analysis_status["started"] = str(datetime.datetime.now())
        analysis_status["log"] = ""
        analysis_status["proc"] = proc
        analysis_status["stages"] = {
            "fetch": {"label": "Fetching RSS", "icon": "📡", "done": False, "count": 0, "detail": ""},
            "classify": {"label": "Classifying", "icon": "🧠", "done": False, "count": 0, "detail": ""},
            "cluster": {"label": "Clustering", "icon": "🔗", "done": False, "count": 0, "detail": ""},
            "phase": {"label": "Determining Phases", "icon": "🗺️", "done": False, "count": 0, "detail": ""},
            "narrative": {"label": "Generating Narratives", "icon": "📝", "done": False, "count": 0, "detail": ""},
            "shift": {"label": "Detecting Shifts", "icon": "🔍", "done": False, "count": 0, "detail": ""},
            "translate": {"label": "Translating", "icon": "🌐", "done": False, "count": 0, "detail": ""},
            "output": {"label": "Writing Output", "icon": "💾", "done": False, "count": 0, "detail": ""},
        }
        analysis_status["current_stage"] = None
        analysis_status["pct"] = 0
        TIMEOUT = 30 * 60
        deadline = time.time() + TIMEOUT
        buf = b""
        while True:
            if time.time() > deadline:
                print(f"\n  [Analysis] TIMEOUT after {TIMEOUT}s, killing PID {proc.pid}")
                proc.kill()
                break
            ch = proc.stdout.read(1)
            if not ch:
                break
            buf += ch
            while b"\n" in buf:
                line, buf = buf.split(b"\n", 1)
                text = line.decode("utf-8", errors="replace").rstrip()
                if text:
                    log_lines.append(text)
                    print(f"  [Analysis] {text}")
                    analysis_status["log"] = "\n".join(log_lines)
                    _parse_log_line(text, analysis_status["stages"], analysis_status)
        proc.stdout.close()
        proc.wait()
        analysis_status["running"] = False
        analysis_status["log"] = "\n".join(log_lines)
        analysis_status["pct"] = 100
        print(f"\n  [Analysis] Done (exit code {proc.returncode})")
        # Invalidate data cache so fresh data is loaded
        _cached_data = None
    except Exception as e:
        analysis_status["running"] = False
        analysis_status["log"] = "\n".join(log_lines) + f"\nError: {e}"
        _cached_data = None

def load_data():
    """Load data from app/data.json (cached)."""
    global _cached_data
    if _cached_data is not None:
        return _cached_data
    try:
        with open(DATA_SOURCE, "r", encoding="utf-8") as f:
            _cached_data = json.load(f)
        print(f"  [test] Loaded data.json ({len(json.dumps(_cached_data))} bytes)")
        return _cached_data
    except FileNotFoundError:
        print(f"  [test] WARNING: {DATA_SOURCE} not found")
        return None
    except json.JSONDecodeError as e:
        print(f"  [test] WARNING: Invalid JSON in data.json: {e}")
        return None

# ── HTTP Handler ───────────────────────────────────────
class TestHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, directory=None, **kwargs):
        super().__init__(*args, directory=str(SERVE_DIR), **kwargs)

    def _json_response(self, data):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        # Proxy /data.json → serve raw file (fast, no JSON parse/dump)
        if self.path == "/data.json":
            if DATA_SOURCE.exists():
                raw = DATA_SOURCE.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "application/json; charset=utf-8")
                self.send_header("Content-Length", str(len(raw)))
                self.send_header("Cache-Control", "no-cache")
                self.end_headers()
                self.wfile.write(raw)
            else:
                self.send_response(404)
                self.end_headers()
            return

        # Proxy /translations.json
        if self.path == "/translations.json":
            trans_file = SERVE_DIR / "translations.json"
            if trans_file.exists():
                self.send_response(200)
                self.send_header("Content-Type", "application/json; charset=utf-8")
                self.end_headers()
                self.wfile.write(trans_file.read_bytes())
            else:
                self.send_response(404)
                self.end_headers()
            return

        # Admin API endpoints
        if self.path == "/api/admin/data":
            data = load_data()
            self._json_response(data if data else {"error": "data.json not found"})
            return
        if self.path == "/api/admin/categories":
            if CATEGORIES_FILE.exists():
                cats = json.loads(CATEGORIES_FILE.read_text(encoding="utf-8"))
                self._json_response(cats)
            else:
                self._json_response([])
            return
        if self.path == "/api/admin/prompts":
            if PROMPTS_FILE.exists():
                self._json_response(json.loads(PROMPTS_FILE.read_text(encoding="utf-8")))
            else:
                self._json_response({})
            return
        if self.path == "/api/admin/taxonomy":
            if TAXONOMY_FILE.exists():
                tax = json.loads(TAXONOMY_FILE.read_text(encoding="utf-8"))
                self._json_response(tax.get("categories", tax) if isinstance(tax, dict) else tax)
            else:
                self._json_response([])
            return
        if self.path == "/api/admin/ai-health":
            self._json_response({"status": "healthy", "totalClassified": 0, "refusals": 0,
                "refusalRate": 0, "lastRun": int(time.time() * 1000)})
            return
        if self.path == "/api/admin/auto-update":
            self._json_response({"enabled": False, "deploy": False,
                "fast": {"enabled": False, "interval": 3600, "last_run": None, "next_run": None,
                         "last_run_str": "\u2014", "next_run_str": "\u2014"},
                "daily": {"enabled": False, "interval": 86400, "last_run": None, "next_run": None,
                          "last_run_str": "\u2014", "next_run_str": "\u2014"}})
            return

        # Analysis status
        if self.path == "/api/analysis/status":
            status = {k: v for k, v in analysis_status.items() if k != "proc"}
            self._json_response(status)
            return

        # Analysis run — also handle GET (admin panel uses fetch without method)
        if self.path.startswith("/api/analysis/run"):
            qs = self.path.split('?')[1] if '?' in self.path else ''
            params = dict(p.split('=') for p in qs.split('&') if '=' in p)
            mode = params.get("mode", "--fast")
            if analysis_status["running"]:
                proc = analysis_status.get("proc")
                if proc and proc.poll() is not None:
                    analysis_status["running"] = False
                if analysis_status["running"]:
                    self._json_response({"error": "analysis already running"})
                    return
                t = threading.Thread(target=run_analysis, args=(mode,), daemon=True)
                t.start()
                self._json_response({"message": f"analysis started (mode={mode})"})
            else:
                t = threading.Thread(target=run_analysis, args=(mode,), daemon=True)
                t.start()
                self._json_response({"message": f"analysis started (mode={mode})"})
            return

        # Analysis cancel
        if self.path == "/api/analysis/cancel":
            proc = analysis_status.get("proc")
            if proc and proc.poll() is None:
                proc.kill()
            analysis_status["running"] = False
            self._json_response({"message": "analysis cancelled"})
            return

        # favicon.ico — suppress browser request
        if self.path == "/favicon.ico":
            self.send_response(204)
            self.end_headers()
            return

        # Admin panel
        if self.path.startswith("/admin"):
            admin_file = PROJECT_ROOT / "admin" / "index.html"
            if admin_file.exists():
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.end_headers()
                self.wfile.write(admin_file.read_bytes())
            else:
                self.send_response(404)
                self.end_headers()
            return

        # Default: serve from test/app/ (no cache)
        self.send_response(200)
        path = self.path.lstrip("/")
        if not path:
            path = "index.html"
        filepath = os.path.join(SERVE_DIR, path)
        if os.path.isfile(filepath):
            mime = {
                ".html": "text/html", ".js": "application/javascript",
                ".css": "text/css", ".json": "application/json",
                ".png": "image/png", ".jpg": "image/jpeg",
                ".svg": "image/svg+xml", ".woff2": "font/woff2",
            }.get(os.path.splitext(filepath)[1], "text/plain")
            self.send_header("Content-Type", f"{mime}; charset=utf-8")
            self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
            self.end_headers()
            with open(filepath, "rb") as f:
                self.wfile.write(f.read())
        else:
            super().do_GET()

    def do_POST(self):
        content_length = int(self.headers.get('Content-Length', 0))
        body = self.rfile.read(content_length) if content_length > 0 else b'{}'
        data = json.loads(body.decode('utf-8'))

        if self.path == "/api/admin/narrative":
            sol_id = data.get("solutionId", "")
            field = data.get("field", "")
            value = data.get("value")
            try:
                if not DATA_SOURCE.exists():
                    self._json_response({"error": "data.json not found"})
                    return
                data_json = json.loads(DATA_SOURCE.read_text(encoding="utf-8"))
                sol = next((s for s in data_json.get("solutions", []) if s["id"] == sol_id), None)
                if not sol:
                    self._json_response({"error": f"Solution '{sol_id}' not found"})
                    return
                if "narrative" not in sol:
                    sol["narrative"] = {}
                sol["narrative"][field] = value
                DATA_SOURCE.write_text(json.dumps(data_json, indent=2, ensure_ascii=False), encoding="utf-8")
                self._json_response({"ok": True})
            except Exception as e:
                self._json_response({"error": str(e)})
            return
        if self.path == "/api/admin/narratives-save":
            try:
                if not DATA_SOURCE.exists():
                    self._json_response({"error": "data.json not found"})
                    return
                data_json = json.loads(DATA_SOURCE.read_text(encoding="utf-8"))
                incoming = {s["id"]: s.get("narrative") for s in data.get("solutions", []) if s.get("narrative")}
                for sol in data_json.get("solutions", []):
                    if sol["id"] in incoming and incoming[sol["id"]]:
                        sol["narrative"] = incoming[sol["id"]]
                DATA_SOURCE.write_text(json.dumps(data_json, indent=2, ensure_ascii=False), encoding="utf-8")
                self._json_response({"ok": True, "saved": len(incoming)})
            except Exception as e:
                self._json_response({"error": str(e)})
            return
        if self.path == "/api/admin/categories":
            action = data.get("action", "")
            if action == "add":
                try:
                    cats = json.loads(CATEGORIES_FILE.read_text(encoding="utf-8")) if CATEGORIES_FILE.exists() else []
                    cats.append({"id": data.get("id", ""), "name": data.get("name", ""), "phases": data.get("phases", []), "core": data.get("core", True)})
                    CATEGORIES_FILE.write_text(json.dumps(cats, indent=2, ensure_ascii=False), encoding="utf-8")
                    self._json_response({"ok": True})
                except Exception as e:
                    self._json_response({"error": str(e)})
            elif action == "update":
                try:
                    cats = json.loads(CATEGORIES_FILE.read_text(encoding="utf-8"))
                    for cat in cats:
                        if cat["id"] == data.get("id"):
                            for k in ("name", "phases", "core"):
                                if k in data:
                                    cat[k] = data[k]
                            break
                    CATEGORIES_FILE.write_text(json.dumps(cats, indent=2, ensure_ascii=False), encoding="utf-8")
                    self._json_response({"ok": True})
                except Exception as e:
                    self._json_response({"error": str(e)})
            elif action == "delete":
                try:
                    cats = json.loads(CATEGORIES_FILE.read_text(encoding="utf-8"))
                    cats = [c for c in cats if c["id"] != data.get("id")]
                    CATEGORIES_FILE.write_text(json.dumps(cats, indent=2, ensure_ascii=False), encoding="utf-8")
                    self._json_response({"ok": True})
                except Exception as e:
                    self._json_response({"error": str(e)})
            return
        if self.path == "/api/admin/prompts":
            try:
                key = data.get("key", "")
                value = data.get("value")
                prompts = json.loads(PROMPTS_FILE.read_text(encoding="utf-8")) if PROMPTS_FILE.exists() else {}
                if key and value is not None:
                    prompts[key] = value
                PROMPTS_FILE.write_text(json.dumps(prompts, indent=2, ensure_ascii=False), encoding="utf-8")
                self._json_response({"ok": True})
            except Exception as e:
                self._json_response({"error": str(e)})
            return
        if self.path == "/api/admin/auto-update":
            self._json_response({"ok": True, "message": "Auto-update not available in test environment"})
            return
        if self.path == "/api/admin/deploy":
            self._json_response({"ok": False, "error": "Deploy not available in test environment"})
            return

        self.send_error(404, "Not found")

    def log_message(self, format, *args):
        print(f"  [test] {self.address_string()} - {format % args}")

# ── Auto-reload data check ─────────────────────────────
def data_watch():
    """Periodically check if data.json changed, print notification."""
    last_hash = None
    while True:
        time.sleep(10)
        try:
            data = load_data()
            if data:
                h = hash(json.dumps(data, sort_keys=True))
                if h != last_hash:
                    print(f"  [test] data.json updated ({time.strftime('%H:%M:%S')})")
                    last_hash = h
        except Exception:
            pass

# ── Main ───────────────────────────────────────────────
if __name__ == "__main__":
    print(f"\n  Serving Peace Paths (test) on http://localhost:{PORT}")
    print(f"  Data source: {DATA_SOURCE}")
    print(f"  Frontend: {SERVE_DIR}")
    print(f"  Press Ctrl+C to stop\n")

    # Start data watcher
    threading.Thread(target=data_watch, daemon=True).start()

    server = http.server.ThreadingHTTPServer(("localhost", PORT), TestHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n  [test] Stopping...")
        server.server_close()
